apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: http-8080
  selector:
    app: {{ .Values.name }}
    deploymentconfig: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
